name = "QuantumStates"
uuid = "0a1581c1-ab82-4660-a1be-26f7b3483457"
authors = ["ttolppanen <taneli.tolppanen@gmail.com>"]
version = "0.1.6"

[deps]
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
